version: "3.8"

services:
  app:
    build: .
    container_name: secure-crypto-service
    ports:
      - "8080:8080"
    volumes:
      - seed-data:/data
      - cron-output:/cron
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro
    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
